"use strict";
Object.defineProperty(exports, "__esModule", {
    value: !0
}), function(target, all) {
    for(var name in all)Object.defineProperty(target, name, {
        enumerable: !0,
        get: all[name]
    });
}(exports, {
    virtualAssetIdFlag: ()=>virtualAssetIdFlag,
    virtualAssetIdPlaceholder: ()=>virtualAssetIdPlaceholder,
    ADDRESS_BIT_LEN: ()=>ADDRESS_BIT_LEN,
    INPUT_ASSET_ID_A_LEN: ()=>INPUT_ASSET_ID_A_LEN,
    OUTPUT_ASSET_ID_A_LEN: ()=>OUTPUT_ASSET_ID_A_LEN,
    OUTPUT_ASSET_ID_B_LEN: ()=>OUTPUT_ASSET_ID_B_LEN,
    INPUT_ASSET_ID_B_LEN: ()=>INPUT_ASSET_ID_B_LEN,
    BITCONFIG_LEN: ()=>BITCONFIG_LEN,
    AUX_DATA_LEN: ()=>AUX_DATA_LEN,
    ADDRESS_OFFSET: ()=>ADDRESS_OFFSET,
    INPUT_ASSET_ID_A_OFFSET: ()=>INPUT_ASSET_ID_A_OFFSET,
    INPUT_ASSET_ID_B_OFFSET: ()=>INPUT_ASSET_ID_B_OFFSET,
    OUTPUT_ASSET_ID_A_OFFSET: ()=>OUTPUT_ASSET_ID_A_OFFSET,
    OUTPUT_ASSET_ID_B_OFFSET: ()=>OUTPUT_ASSET_ID_B_OFFSET,
    BITCONFIG_OFFSET: ()=>BITCONFIG_OFFSET,
    AUX_DATA_OFFSET: ()=>AUX_DATA_OFFSET
});
const virtualAssetIdFlag = 536870912, virtualAssetIdPlaceholder = 536870912, ADDRESS_BIT_LEN = 32, INPUT_ASSET_ID_A_LEN = 30, OUTPUT_ASSET_ID_A_LEN = 30, OUTPUT_ASSET_ID_B_LEN = 30, INPUT_ASSET_ID_B_LEN = 30, BITCONFIG_LEN = 32, AUX_DATA_LEN = 64, ADDRESS_OFFSET = 0, INPUT_ASSET_ID_A_OFFSET = ADDRESS_BIT_LEN, INPUT_ASSET_ID_B_OFFSET = INPUT_ASSET_ID_A_OFFSET + INPUT_ASSET_ID_A_LEN, OUTPUT_ASSET_ID_A_OFFSET = INPUT_ASSET_ID_B_OFFSET + INPUT_ASSET_ID_B_LEN, OUTPUT_ASSET_ID_B_OFFSET = OUTPUT_ASSET_ID_A_OFFSET + OUTPUT_ASSET_ID_A_LEN, BITCONFIG_OFFSET = OUTPUT_ASSET_ID_B_OFFSET + OUTPUT_ASSET_ID_B_LEN, AUX_DATA_OFFSET = BITCONFIG_OFFSET + BITCONFIG_LEN;
